tests
testMessages
	^ '[10:13] <discord> i added those to the sources list
[10:13] <Liberal_Tugboat> ok I think I need to hit the hay, go snuggle up next to my nice warm nekid fiance and get some sleep
[10:14] <crimsun> Kazuhiro: (hmm, just "pwd" without the quotes)
[10:14] <discord> more than i ned
[10:14] <Liberal_Tugboat> hmm
[10:14] <discord> anyone else
[10:14] <Liberal_Tugboat> and it wont install
[10:14] <crimsun> Kazuhiro: ok, cd /usr/src && sudo tar xfj alsa-driver.tar.bz2
[10:14] <discord> i added
[10:14] <Kazuhiro> crimsun, /'.